import { BaseEntity } from './BaseEntity';
import { TokenStatus, EducationLevel } from '../enums';

/**
 * Registration Token Interface
 * Used for org-ward registration with tokens generated by org admins
 */
export interface RegistrationToken extends BaseEntity {
  token: string; // The unique token string
  generated_by_user_id: string; // Foreign key to User table (ORG_ADMIN who generated token)
  organization_id: string; // Foreign key to Organization table
  status: TokenStatus;
  used_by_user_id?: string; // Foreign key to User table (ORG_WARD who used token)
  student_name?: string; // Intended student name
  student_email?: string; // Intended student email
  education_level?: EducationLevel; // Intended education level
  max_uses: number; // Maximum number of times token can be used
  current_uses: number; // Current number of uses
  expires_at: Date;
  used_at?: Date;
  is_soft_deleted?: boolean;
  soft_deleted_at?: Date;
}
