-- Seed resources data
INSERT INTO resources (
    title, description, full_description, category, type, resource_type, 
    rating, link, featured, image, features, duration, difficulty, tags, free
) VALUES 
-- Student Resources
(
    'Career Assessment Tools',
    'Discover your interests, skills, and potential career paths',
    'Our comprehensive career assessment tools help you understand your personality, interests, values, and skills to identify potential career paths that align with who you are. These scientifically-backed assessments provide detailed reports and personalized recommendations to guide your career exploration journey.',
    'Assessment',
    'Interactive',
    'students',
    4.8,
    'https://example.com/career-assessment',
    true,
    '/placeholder.svg?height=400&width=600',
    '["Personality assessment based on Holland Code theory", "Skills inventory and gap analysis", "Values clarification exercises", "Personalized career recommendations", "Detailed PDF reports"]'::jsonb,
    '30-45 minutes',
    'Beginner',
    '["career", "assessment", "personality"]'::jsonb,
    true
),
(
    'Resume Builder & Templates',
    'Professional resume templates and building tools',
    'Create professional, ATS-friendly resumes with our collection of modern templates and intuitive builder tool. Whether you''re a recent graduate or changing careers, our platform provides step-by-step guidance to showcase your experience effectively.',
    'Job Prep',
    'Tool',
    'students',
    4.7,
    'https://example.com/resume-builder',
    false,
    '/placeholder.svg?height=400&width=600',
    '["20+ professional templates", "ATS-optimization checker", "Real-time editing and preview", "Export to PDF and Word formats", "Industry-specific examples"]'::jsonb,
    '15-30 minutes',
    'Beginner',
    '["resume", "job-prep", "templates"]'::jsonb,
    true
),
(
    'Interview Preparation Guide',
    'Tips, common questions, and practice scenarios',
    'Master the art of interviewing with our comprehensive preparation guide. From behavioral questions to technical interviews, we provide strategies, sample answers, and practice opportunities to boost your confidence.',
    'Job Prep',
    'Guide',
    'students',
    4.9,
    'https://example.com/interview-prep',
    false,
    '/placeholder.svg?height=400&width=600',
    '["500+ common interview questions", "STAR method framework", "Video practice sessions", "Industry-specific scenarios", "Mock interview scheduling"]'::jsonb,
    '2-3 hours',
    'Intermediate',
    '["interview", "job-prep", "practice"]'::jsonb,
    true
),
(
    'Industry Exploration Hub',
    'Explore different industries and career opportunities',
    'Dive deep into various industries to understand career opportunities, growth trends, salary expectations, and required skills. Our comprehensive database covers traditional and emerging fields.',
    'Exploration',
    'Database',
    'students',
    4.6,
    'https://example.com/industry-hub',
    false,
    '/placeholder.svg?height=400&width=600',
    '["50+ industry profiles", "Salary and growth data", "Required skills breakdown", "Day-in-the-life videos", "Professional interviews"]'::jsonb,
    '1-2 hours per industry',
    'Beginner',
    '["industry", "exploration", "careers"]'::jsonb,
    true
),
(
    'Scholarship & Financial Aid',
    'Find funding opportunities for your education',
    'Access our comprehensive database of scholarships, grants, and financial aid opportunities. Filter by criteria that match your background, interests, and academic achievements.',
    'Financial',
    'Database',
    'students',
    4.5,
    'https://example.com/scholarships',
    false,
    '/placeholder.svg?height=400&width=600',
    '["10,000+ scholarship opportunities", "Personalized matching algorithm", "Application deadline tracking", "Essay writing assistance", "Financial aid calculator"]'::jsonb,
    'Ongoing',
    'Beginner',
    '["scholarships", "financial-aid", "education"]'::jsonb,
    true
),
(
    'Networking & Mentorship',
    'Connect with professionals in your field of interest',
    'Build meaningful professional relationships through our networking platform. Connect with industry professionals, find mentors, and participate in virtual networking events.',
    'Networking',
    'Platform',
    'students',
    4.4,
    'https://example.com/networking',
    false,
    '/placeholder.svg?height=400&width=600',
    '["Professional mentor matching", "Industry networking events", "LinkedIn optimization tips", "Informational interview guides", "Professional communication templates"]'::jsonb,
    'Ongoing',
    'Intermediate',
    '["networking", "mentorship", "professionals"]'::jsonb,
    true
),

-- Parent Resources
(
    'Supporting Your Teen''s Career Journey',
    'A comprehensive guide for parents on career guidance',
    'Learn how to effectively support your teenager''s career exploration without overwhelming them. This guide provides practical strategies for meaningful conversations, understanding their interests, and helping them make informed decisions.',
    'Guidance',
    'Guide',
    'parents',
    4.8,
    'https://example.com/teen-support',
    true,
    '/placeholder.svg?height=400&width=600',
    '["Age-appropriate conversation starters", "Understanding generational differences", "Supporting without pressuring", "Recognizing signs of career anxiety", "Building confidence and independence"]'::jsonb,
    '1-2 hours',
    'Beginner',
    '["parenting", "teen-support", "career-guidance"]'::jsonb,
    true
),
(
    'Understanding Career Assessments',
    'How to interpret and discuss career assessment results',
    'Decode career assessment results and learn how to have productive discussions with your teen about their findings. Understand the science behind assessments and how to use results constructively.',
    'Assessment',
    'Article',
    'parents',
    4.7,
    'https://example.com/assessment-guide',
    false,
    '/placeholder.svg?height=400&width=600',
    '["Assessment types explained", "Interpreting personality results", "Discussing strengths and challenges", "Action planning from results", "When to seek professional help"]'::jsonb,
    '45 minutes',
    'Beginner',
    '["assessment", "interpretation", "guidance"]'::jsonb,
    true
),
(
    'College vs. Trade School Discussion',
    'Helping your child explore all post-secondary options',
    'Navigate the complex landscape of post-secondary education options. Understand the benefits of different paths and help your teen make decisions based on their goals, interests, and circumstances.',
    'Education',
    'Video',
    'parents',
    4.6,
    'https://example.com/education-options',
    false,
    '/placeholder.svg?height=400&width=600',
    '["4-year college overview", "Community college benefits", "Trade school opportunities", "Alternative education paths", "ROI analysis tools"]'::jsonb,
    '2 hours',
    'Intermediate',
    '["education", "college", "trade-school"]'::jsonb,
    true
),

-- Counselor Resources
(
    'Career Counseling Best Practices',
    'Evidence-based approaches to career guidance',
    'Stay current with the latest evidence-based practices in career counseling. This comprehensive resource covers theoretical frameworks, practical techniques, and ethical considerations for effective career guidance.',
    'Professional',
    'Training',
    'counselors',
    4.9,
    'https://example.com/best-practices',
    true,
    '/placeholder.svg?height=400&width=600',
    '["Theoretical framework overview", "Evidence-based interventions", "Ethical guidelines and standards", "Cultural competency training", "Outcome measurement tools"]'::jsonb,
    '8 hours',
    'Advanced',
    '["professional-development", "best-practices", "ethics"]'::jsonb,
    true
),
(
    'Assessment Tools & Interpretation',
    'Comprehensive guide to career assessment instruments',
    'Master the use of various career assessment tools and learn to interpret results effectively. This resource covers popular assessments, their applications, and how to communicate findings to clients.',
    'Assessment',
    'Manual',
    'counselors',
    4.8,
    'https://example.com/assessment-tools',
    false,
    '/placeholder.svg?height=400&width=600',
    '["Assessment tool comparison", "Administration guidelines", "Interpretation frameworks", "Report writing templates", "Client feedback strategies"]'::jsonb,
    '6 hours',
    'Advanced',
    '["assessment", "tools", "interpretation"]'::jsonb,
    true
),
(
    'Group Career Counseling Activities',
    'Ready-to-use activities for group sessions',
    'Enhance your group career counseling sessions with these engaging, research-based activities. Each activity includes detailed instructions, materials needed, and learning objectives.',
    'Activities',
    'Resource Pack',
    'counselors',
    4.7,
    'https://example.com/group-activities',
    false,
    '/placeholder.svg?height=400&width=600',
    '["50+ group activities", "Detailed facilitation guides", "Printable worksheets", "Age-appropriate variations", "Assessment rubrics"]'::jsonb,
    'Varies',
    'Intermediate',
    '["group-activities", "facilitation", "worksheets"]'::jsonb,
    true
);
